### ISSUE TITLE
What's the result of mIOU in val/test with your code?

### ISSUE THREAD

**Issue by dreambear1234** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#1]
When I used this code, I reduced 'batch_size' and 'image_size' because my GPU memory is not enough,
batch_size = 7, image_size = 257; unfortunately, I only got 73.2 with mIOU;
additionally, I add a new model(model_msc): multi scale input for train and test, mIOU = 74.2;
they are all far from 76.35(paper's result). 
Could you tell me what the reason might be? 
And, how many mIOU got by your experiment?
thank you very much!

**Comment by zhengyang-wang** [comment]
The batch_size and image_size matters.
I got 75.4 without MSC.

**Comment by dreambear1234** [comment]
for standard input(input_size & batch_size), When I used cpu to run the code, it shows that 23G is occupied(ubuntu-->top-->virt), Is it really need such a huge memory? (my gpu memory size is 10G)
thank you very much!

**Comment by dreambear1234** [comment]
Should I change any parameter? Or just use "python main.py" is okay?
parameter like 'is_training' is also set to default value (false)?
by the way, how many gpu memory is required?

**Comment by zhengyang-wang** [comment]
Only the 'valid_step' needs to be changed if you want the same setting as the paper.
'is_training' is set to false to keep moving mean and moving variance fixed as pretrained. 
My gpu has 11.17GB and it works well.
