### ISSUE TITLE
Bug for create folder

### ISSUE THREAD

**Issue by John1231983** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#14]
This is a bug when someone run prediction in the first time. Because the source code does not have some folder such as `./output/prediction`, `/output/visual_prediction`, `model`. So it is better to provide a short script to generate these folders checkif it is not exist. 

In addition, could you tell me the performance of mIOU did you achieve with multiple scale code in the PASCAL and CITYSCAPE? Thanks for your good job.

**Comment by zhengyang-wang** [comment]
I believe the folders will be created by my code if they do not exist.

**Comment by John1231983** [comment]
Could you update the performance that you achieve when run the msc code?

**Comment by zhengyang-wang** [comment]
For PASCAL, msc obtained mIoU 76.1 (76.35 in the paper).

**Comment by John1231983** [comment]
Thanks. I got it. I just want to ask you a personal question. Do you have any schedule to extend the project to deeplab v3. I think you have a good program skill and write the code very clear, logic. Hope you can spend time to develop the state-of-the-art deeplab v3. Good job!
