### ISSUE TITLE
After training,I did the main.py 's prediction.Why the pictures is black, only have black background!

### ISSUE THREAD

**Issue by xhw205** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#15]

**Comment by xhw205** [comment]
You know, I means the outputs' pictures.

**Comment by John1231983** [comment]
You can see the color output in another folder. It worked well for me

**Comment by xhw205** [comment]
Which datasets  are you using ? And Which places have you changed in this code? I‘’m crashing.........

**Comment by zhengyang-wang** [comment]
Please read the README. All your questions can be answered. Thanks.
For your crashing, I cannot help you without any information.
