### ISSUE TITLE
Apply the code on my own data set

### ISSUE THREAD

**Issue by bkwwangjie** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#18]
What code do I need to change if I want to use your code for segmentation of my gray image? Change the channel, change the size and look forward to your reply

**Comment by zhengyang-wang** [comment]
Hi. As you may know, this model employed transfer learning, which means the encoder is initialized by a pre-trained image classification model. The classification model is for RGB images. So, to use it for gray image inputs, as least you need to change the very first layer. Meanwhile, you need to find another pre-trained model for gray images or train from scratch, which needs much more data.

**Comment by zhengyang-wang** [comment]
Another option is to copy your gray images three times. This will give you inputs with three channels.

**Comment by bkwwangjie** [comment]
I'll try and thank you.
 

我将尝试一下，感谢您







I'll try and thank you.
