### ISSUE TITLE
question about CRFs

### ISSUE THREAD

**Issue by jhtao1860** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#2]
hi Zhengyang，Thanks for your code! here is one question,  did you use CRFs in your code?

**Comment by zhengyang-wang** [comment]
No. CRF is just a post-processing method. It is easy to modify my code to save all the predictions and use other's implementation of CRF (e.g. https://github.com/lucasb-eyer/pydensecrf). Thanks.
