### ISSUE TITLE
tf.flags

### ISSUE THREAD

**Issue by warmestwind** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#3]
Hi zhengyang, I want to know why you set  flags.FLAGS.__dict__['__parsed'] = False in configure( )? What does it mean?
Thank you!

**Comment by zhengyang-wang** [comment]
This was to fix a bug in tensorflow. Without this line, the arguments won't be parsed. I don't know whether it has been fixed. You can delete it and see whether it works now. :)
