### ISSUE TITLE
In predict mode, the output images and file names are not consistent

### ISSUE THREAD

**Issue by Kewenjing1020** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#31]
I shifted to prediction mode for visualization, then I found that the images and file names are not consistent.

**Comment by zhengyang-wang** [comment]
Could you give me an example?

**Comment by Kewenjing1020** [comment]
@zhengyang-wang 
![Uploading 531517554511_.pic_hd.jpg…]()

**Comment by Kewenjing1020** [comment]
![531517554511_ pic_hd](https://user-images.githubusercontent.com/15858931/35721260-1962ba1a-082c-11e8-89f8-dd26bf741c2c.jpg)
@zhengyang-wang

**Comment by zhengyang-wang** [comment]
Thanks for reporting the problem. There seems to be a bug in the code. I'll fix it.

**Comment by zhengyang-wang** [comment]
I tested my code. There is no problem like what you reported.
I have a question. Did you change anything before prediction? The image size of your prediction is 320x320, which is not expected if you use my code without any modification.

**Comment by Kewenjing1020** [comment]
You are right, this problem only happens when I changed the image size.
 @zhengyang-wang

**Comment by Kewenjing1020** [comment]
Oh, I think I found the problem location.
In model.py I modified input_size:
```
    def predict_setup(self):
          ...
          reader = ImageReader(
				self.conf.data_dir,
				self.conf.test_data_list,
			        input_size,       # it was previously set to 'None'
				False, # no data-aug
				False, # no data-aug
				self.conf.ignore_label,
				IMG_MEAN,
				self.coord)
   ```    
While in image_reader.py:
```
    def __init__(...)
         ...
         self.queue = tf.train.slice_input_producer([self.images, self.labels],
                                                   shuffle=input_size is not None)
```
So the image reader returns random batch, this explains why the image content and file name are not consistent.
Thank you for your reply. @zhengyang-wang
