### ISSUE TITLE
使用自己的数据集时，mIoU的值很低

### ISSUE THREAD

**Issue by yyz97** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#36]
您好，非常感谢您的代码。当我使用PASCAL VOC数据集时，mIoU和最终的预测像素值表现的比较好;但是当我用自己的数据集时，loss虽然下降了，但是mIoU的值非常低，如下图
![1](https://user-images.githubusercontent.com/32064841/36352686-b11871ba-14f7-11e8-9ae4-c59d1358d895.jpg)
我自己的数据集比较小，训练集和验证集都只有100张左右;而且图片分辨率是640X480;这些图片基本上一致，如下图
![1](https://user-images.githubusercontent.com/32064841/36352702-dc073686-14f7-11e8-9d70-b164f905b6cd.png)

希望大神帮忙看看，十分感谢！

**Comment by zhengyang-wang** [comment]
First, the images in your dataset are not natural images. As we transfer pre-trained ResNet which is trained on ImageNet, it is supposed to use this model on natural image segmentation.
Second, deep learning models usually require a large number of training images. 100 is too small.

I suggest you try some simpler models like U-net, which is trained from scratch and used on small datasets of medical images. Meanwhile, try to increase the size of your datasets.
