### ISSUE TITLE
compute_IoU_per_class

### ISSUE THREAD

**Issue by SLtila** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#37]
when i use compute_IoU_per_class function, there is such problem:

print('class %d: %.3f'%(i,IoU))
TypeError: a float is required
how can  i fix it?
thanks a lot

**Comment by zhengyang-wang** [comment]
Obviously this is a type error. To directly fix it, just change the dtype of IoU.
Did you change the code? I didn't encounter this problem.
