### ISSUE TITLE
Getting error 'FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)'

### ISSUE THREAD

**Issue by cclough** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#4]
When I run main.py I get:

`OutOfRangeError (see above for traceback): FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
         [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]`

I've downloaded VOC and have the path in main.py set to:
`flags.DEFINE_string('data_dir', './VOCdevkit/VOC2012', 'data directory')`

I've also set the following in main.py:
`	flags.DEFINE_string('encoder_name', 'res101', 'name of pre-trained model, res101, res50 or deeplab')
	flags.DEFINE_string('pretrain_file', './resnet_v1_101.ckpt', 'pre-trained model filename corresponding to encoder_name')`

Apologies if I'm doing something obvious wrong.

**Comment by zhengyang-wang** [comment]
I think you may need to check the directory with "./dataset/train.txt" again. For example, is the training image in "./VOCdevkit/VOC2012/JPEGImages/"? The error information means the program cannot find the input.
Thanks for reporting your problem.
