### ISSUE TITLE
fc7 and fc8 layers?

### ISSUE THREAD

**Issue by darbyyyy** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#41]
Though there are fc7 and fc8 layers On Fig. 7 in the deeplab v2 paper, I couldn't find those in your implementation.
Is it my failure to understand the code or it just has not been implemented?

**Comment by zhengyang-wang** [comment]
Good question. Although there are 2 extra 1x1 convolutions named as 'fc7' and 'fc8' in Figure 7 of the paper, their official caffe implementation does not have those layers.
You can check the prototxt (renamed as txt for uploading).
[train_dev.prototxt.txt](https://github.com/zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow/files/1882080/train_dev.prototxt.txt)
