### ISSUE TITLE
TypeErro

### ISSUE THREAD

**Issue by piaopiaow** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#44]
Hello, what is the format of your data? Can you upload the data set you use. I always get the error "TypeError: Value passed to parameter 'x' has DataType uint8 not in list of allowed values: float16, float32, float64, int32, int64, complex64, complex128"

**Comment by zhengyang-wang** [comment]
The dataset is PASCAL VOC 2012 which is publicly available. Your problem seems to be a dtype inconsistent problem which can be directly solved by using tf.cast. Thanks.
