### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by shapera-lab** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#47]
你好，为什么我下载的数据集只有2000多张分割的图片，代码里的train.txt有10000多张，是我下载的数据集不对吗

**Comment by shapera-lab** [comment]
找到了

**Comment by VicQwz** [comment]
那个SegmentationAug是啥版本啊

**Comment by zhengyang-wang** [comment]
https://www.dropbox.com/s/oeu149j8qtbs1x0/SegmentationClassAug.zip?dl=0
