### ISSUE TITLE
Another dataset

### ISSUE THREAD

**Issue by mhusseinsh** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#49]
Hello,
I want to ask, if there is a possibility to use your deep lab implementation on my own dataset for semantic segmentation task.
I have a dataset with semantic segmentation labels of 12 classes, is it possible to use your model ?

**Comment by zhengyang-wang** [comment]
It is definitely possible. Technically, there are two constraints:
1. The number of your input channels must be 3.
2. The spatial size of your input cannot be too small.

**Comment by mhusseinsh** [comment]
@zhengyang-wang  you mean the semantic segmentation labels ?
my images are RGB, and the labels are RGB images also, but encoded the R channel

**Comment by zhengyang-wang** [comment]
I don't quite understand. Your input images are RGB, which is fine. However, for a segmentation task, the label should have the same spatial size as your input image, and the value of each pixel should be integers between [0,11] since you have 12 classes.

**Comment by zhengyang-wang** [comment]
And the label should not be RGB. It should only contains one channel.
