### ISSUE TITLE
Problem with pre-trained model

### ISSUE THREAD

**Issue by daicoolb** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#50]
Hey, I want to use resnet v2 to train deeplab v2. Now , I have doubt about the pre-trained model.
From your code , you mentioned deeplab_resnet.ckpt and resnet101.ckpt,  Can I just use the resnet101.ckpt as the initialize model to train deeplab v2 . If it works, then I can use the resnet v2 to train deeplab_v2

**Comment by zhengyang-wang** [comment]
You can use any ckpt to initialize the model as long as they have the same network architecture.
