### ISSUE TITLE
Training Cityscapes - Changes in label_utils.py  

### ISSUE THREAD

**Issue by TheDog223** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#52]
@zhengyang-wang  I am trying to build my model using Cityscapes dataset. Because of the dataset's structure :

https://github.com/mcordts/cityscapesScripts/blob/4031404ae3dffe901f45a91f7bb0253389284d6f/cityscapesscripts/helpers/labels.py

some labels should be ignored in evaluation. How is this possible using your code? I can see that you ignore just 255 class. Is it possible to do this without changing the whole data-label preprocessing?

**Comment by zhengyang-wang** [comment]
According to your link,

> Please adapt the train IDs as appropriate for your approach.
> Note that you might want to ignore labels with ID 255 during training.
> Further note that the current train IDs are only a suggestion. You can use whatever you like.
> Make sure to provide your results using the original IDs and not the training IDs.
> Note that many IDs are ignored in evaluation and thus you never need to predict these!


Only 19 classes are used in evaluation. For self-evaluation, you need to ignore 255 and -1, which can easily be achieved by using the [weights](https://github.com/zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow/blob/c9a9fbc47feb825a085c93b5615cdcfd483c8c50/model.py#L313) arguments. If you want to upload your results, you need to map "trainId" back to original "id".
