### ISSUE TITLE
How to process the outline of the object in Segmentation label images?

### ISSUE THREAD

**Issue by wangq95** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#54]
Hi, I have a question about the VOC 2012 Segmentation train database. The outline of the object with rgb =(224,224,192) is not in the class list, how to process them during training? Is to ignore them as a 'ignore label'? Then how to process them during TEST procedure? Thank you very much!

**Comment by zhengyang-wang** [comment]
Only labels between [0,20] will count for training and testing. Other values will be ignored.

Check [line](https://github.com/zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow/blob/9fabb283377ef4460dfe127be9b81c068ac29baf/model.py#L210) and [line](https://github.com/zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow/blob/9fabb283377ef4460dfe127be9b81c068ac29baf/model.py#L311).
