### ISSUE TITLE
 The problem about paper "Smoothed Dilated Convolutions for Improved Dense Prediction".

### ISSUE THREAD

**Issue by CS-Jackson** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#55]
Hi, @zhengyang-wang. Thanks for the works. I was wondering if you try to impelement the model in the paper using pytorch, because it seems have no the API like tf.space_to_batch and tf.batch_to_space. Can you give me any advice?

**Comment by zhengyang-wang** [comment]
I'm sorry that I am not familiar with pytorch. You may want to explore using appropriate reshape to achieve the same effect.
