### ISSUE TITLE
Which part of your code corresponds to the CRF in Deeplab V2?

### ISSUE THREAD

**Issue by hnyz979** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#56]
Dear Wang~
Nice reading your codes. I am now learning the combination of DCNNs with CRFs, so I am very interested in Deeplab. It is very nice of you to re-implement it in tensorflow. However, I am a little confused that which part of your code corresponds to CRF in Deeplab V2? It seems that the model ends after the ASPP in "networks.py", and I did not find the CRF conbimed to the CNN's.
Could you help me with it? Thank you a lot!

**Comment by zhengyang-wang** [comment]
I did not implement CRF since it is a separate post-processing step. I only focused on the deep learning part. If you want to use CRF, you can refer to https://github.com/DrSleep/tensorflow-deeplab-resnet/tree/crf
