### ISSUE TITLE
A question about paper "Smoothed Dilated Convolutions for Improved Dense Prediction"

### ISSUE THREAD

**Issue by lxsyz** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#58]
@zhengyang-wang Hello! Thanks for your works!
I'm wondering how to deal with 3D data like [batch, length,  filters] because I find that the function space_to_batch() can only get the 4D input. 
I'm trying to implement your method in one-dimentional cases. And I want to use conv1d to deal with the data. I don't want to reshape, so could you give me some advice? Thanks you very much!

**Comment by zhengyang-wang** [comment]
Thank you for your interest!
Have you tried [batch_to_space_nd](https://www.tensorflow.org/api_docs/python/tf/batch_to_space_nd) ?
I didn't explore this API. But from the documentation, it might be what you want.

**Comment by lxsyz** [comment]
Thank you. I have solved it.
