### ISSUE TITLE
  NewRandomAccessFile failed to Create/Open: E:\Datase\VOC2012 : 拒绝访问,

### ISSUE THREAD

**Issue by warmestwind** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#6]
Hi zhengyang, I run your code in windows, and I set 
flags.DEFINE_string('data_dir','E:\Dataset\VOC2012','data directory').
Then, I get the   NewRandomAccessFile failed to Create/Open: E:\Datase\VOC2012 : 拒绝访问,
and OutOfRangeError: FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)  ,which same as @cclough.
It is very confuse me, can you can tell me where I was wrong?
Thank you!!!!

**Comment by zhengyang-wang** [comment]
It shows that the program did not have access to your input folder. So for the program, no input could be read. That's why you got the same error info.
