### ISSUE TITLE
Can I input 6 channel images for training?

### ISSUE THREAD

**Issue by VicQwz** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#61]
What changes do I need to make to the model?
I am a beginner, thank you and wish a happy life!

**Comment by zhengyang-wang** [comment]
As we are using transfer learning here, there is no perfect way to handle inputs with different number of channels. At least, you need to change the very first layer and train it from scratch.

**Comment by VicQwz** [comment]
Thanks！
