### ISSUE TITLE
ABOUT BATCHSIZE WHEN TRAINING ON CITYSCAPES

### ISSUE THREAD

**Issue by jwnirvana** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#65]
-----------build encoder: deeplab pre-trained-----------
after start block: (3, 179, 179, 64)
after block1: (3, 179, 179, 256)
after block2: (3, 90, 90, 512)
after block3: (3, 90, 90, 1024)
after block4: (3, 90, 90, 2048)
-----------build decoder-----------
after aspp block: (3, 90, 90, 19)
WARNING:tensorflow:From /media/wj/bangong/wang/Deeplab-v2--ResNet-101--Tensorflow-master/model.py:262: calling expand_dims (from tensorflow.python.ops.array_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
Restored model parameters from ../reference model/deeplab_resnet_init.ckpt
WARNING:tensorflow:From /media/wj/bangong/wang/Deeplab-v2--ResNet-101--Tensorflow-master/model.py:45: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Traceback (most recent call last):
  File "/home/wj/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/wj/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/wj/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[3,90,90,2048] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node res5a_branch1/Conv2D-0-1-TransposeNCHWToNHWC-LayoutOptimizer}} = Transpose[T=DT_FLOAT, Tperm=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](res5a_branch1/Conv2D, PermConstNCHWToNHWC-LayoutOptimizer)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[{{node add/_1131}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_6957_add", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_city.py", line 81, in <module>
    tf.app.run()
  File "/home/wj/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main_city.py", line 73, in main
    getattr(model, args.option)()
  File "/media/wj/bangong/wang/Deeplab-v2--ResNet-101--Tensorflow-master/model.py", line 60, in train
    feed_dict=feed_dict)
  File "/home/wj/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/wj/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/wj/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/wj/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[3,90,90,2048] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node res5a_branch1/Conv2D-0-1-TransposeNCHWToNHWC-LayoutOptimizer}} = Transpose[T=DT_FLOAT, Tperm=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](res5a_branch1/Conv2D, PermConstNCHWToNHWC-LayoutOptimizer)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[{{node add/_1131}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_6957_add", tensor_type=DT_FLOAT, 

- [ ] 

- [ ] _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

- 

**************************************************************************************************
MY PARMS SETTING:
# training
	flags.DEFINE_integer('num_steps', 50000, 'maximum number of iterations')
	flags.DEFINE_integer('save_interval', 10000, 'number of iterations for saving and visualization')
	flags.DEFINE_integer('random_seed', 1234, 'random seed')
	flags.DEFINE_float('weight_decay', 0.0001, 'weight decay rate')
	flags.DEFINE_float('learning_rate', 1e-3, 'learning rate')
	flags.DEFINE_float('power', 0.9, 'hyperparameter for poly learning rate')
	flags.DEFINE_float('momentum', 0.9, 'momentum')
	flags.DEFINE_string('encoder_name', 'deeplab', 'name of pre-trained model, res101, res50 or deeplab')
	flags.DEFINE_string('pretrain_file', '../reference model/deeplab_resnet_init.ckpt', 'pre-trained model filename corresponding to encoder_name')
	flags.DEFINE_string('data_list', './dataset_cityscapes/train_fine.txt', 'training data list filename')

	# validation
	flags.DEFINE_integer('valid_step', 40000, 'checkpoint number for validation')
	flags.DEFINE_integer('valid_num_steps', 500, '= number of validation samples')
	flags.DEFINE_string('valid_data_list', './dataset_cityscapes/val_fine.txt', 'validation data list filename')

	# prediction / saving outputs for testing or validation
	flags.DEFINE_string('out_dir', 'output_cityscapes', 'directory for saving outputs')
	flags.DEFINE_integer('test_step', 40000, 'checkpoint number for testing/validation')
	flags.DEFINE_integer('test_num_steps', 500, '= number of testing/validation samples')
	flags.DEFINE_string('test_data_list', './dataset_cityscapes/val_fine.txt', 'testing/validation data list filename')
	flags.DEFINE_boolean('visual', True, 'whether to save predictions for visualization')

	# data
	flags.DEFINE_string('data_dir', './citydata/cityscapes', 'data directory')
	flags.DEFINE_integer('batch_size', 3, 'training batch size')
	flags.DEFINE_integer('input_height', 713, 'input image height')
	flags.DEFINE_integer('input_width', 713, 'input image width')
	flags.DEFINE_integer('num_classes', 19, 'number of classes')
	flags.DEFINE_integer('ignore_label', 255, 'label pixel value that should be ignored')
	flags.DEFINE_boolean('random_scale', True, 'whether to perform random scaling data-augmentation')
	flags.DEFINE_boolean('random_mirror', True, 'whether to perform random left-right flipping data-augmentation')
	
**************************************************************************************************
parms setting is according to history issue
when I set batchsize=1, error is batchsize should>=2, when batchsize=2, the error is the same as the situation when batchsize=3

**Comment by zhengyang-wang** [comment]
It is OOM. Try reducing input_height and input_width.
