### ISSUE TITLE
It is OOM. Try reducing input_height and input_width.

### ISSUE THREAD

**Issue by jwnirvana** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#66]
Thanks ，I have tried to reduce  h and w to 512*512, but the original picture scale is 1024*2048. is there some problem?(长方形变成正方形，比原图小很多) 。After experiment, the validation miou  on cityscapes is only 68.9. Could you please offer some suggestions for this problem?

**Comment by zhengyang-wang** [comment]
The training uses random cropping. I don't think that is a problem.
