### ISSUE TITLE
resnet101   ------- miou 70.7%

### ISSUE THREAD

**Issue by dxw1997** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#67]
I'm a beginner in image segmentation.Thanks 
for sharing your code.I use the original resnet101 as 
pretrained model, after training for 20000steps, I only 
get miou 70.7%, ，I don't think this is a satisfactory result.
The dataset is pascal voc 2012, can you give me some advice
 for improving the result?
    Other than that, I haven't changed the configuration 
parameters in the code, how can I find better configuration
 parameters?

**Comment by zhengyang-wang** [comment]
Try to read the DeepLab v2 paper where you can find many tricks.
Using the deeplab pretrained model helps.
Using multi-scale helps as well.
Both are enabled in the provided code.

Thanks.

**Comment by dxw1997** [comment]
Thank you very much for your advice.
